# -*- coding: utf-8 -*-
START_TAG = "[CLS]"
END_TAG = "[SEP]"
PAD = "[PAD]"
UNK = "[UNK]"
entity = ['DRUG', 'DISEASE', 'SYMPTOM', 'SYNDROME', 'FOOD', 'DRUG_INGREDIENT', 'DISEASE_GROUP', 'FOOD_GROUP',
          'PERSON_GROUP', 'DRUG_GROUP', 'DRUG_DOSAGE', 'DRUG_TASTE', 'DRUG_EFFICACY']

O = 'O'
BDRUG = 'B-DRUG'
IDRUG = 'I-DRUG'
BDISEASE = 'B-DISEASE'
IDISEASE = 'I-DISEASE'
BSYMPTOM = 'B-SYMPTOM'
ISYMPTOM = 'I-SYMPTOM'
BSYNDROME = 'B-SYNDROME'
ISYNDROME = 'I-SYNDROME'
BFOOD = 'B-FOOD'
IFOOD = 'I-FOOD'
BDRUG_INGREDIENT = 'B-DRUG_INGREDIENT'
IDRUG_INGREDIENT = 'I-DRUG_INGREDIENT'
BDISEASE_GROUP = 'B-DISEASE_GROUP'
IDISEASE_GROUP = 'I-DISEASE_GROUP'
BFOOD_GROUP = 'B-FOOD_GROUP'
IFOOD_GROUP = 'I-FOOD_GROUP'
BPERSON_GROUP = 'B-PERSON_GROUP'
IPERSON_GROUP = 'I-PERSON_GROUP'
BDRUG_GROUP = 'B-DRUG_GROUP'
IDRUG_GROUP = 'I-DRUG_GROUP'
BDRUG_DOSAGE = 'B-DRUG_DOSAGE'
IDRUG_DOSAGE = 'I-DRUG_DOSAGE'
BDRUG_TASTE = 'B-DRUG_TASTE'
IDRUG_TASTE = 'I-DRUG_TASTE'
BDRUG_EFFICACY = 'B-DRUG_EFFICACY'
IDRUG_EFFICACY = 'I-DRUG_EFFICACY'
tag2indx = {
    O: 0,
    BDRUG: 1,
    IDRUG: 2,
    BDISEASE: 3,
    IDISEASE: 4,
    BSYMPTOM: 5,
    ISYMPTOM: 6,
    BSYNDROME: 7,
    ISYNDROME: 8,
    BFOOD: 9,
    IFOOD: 10,
    BDRUG_INGREDIENT: 11,
    IDRUG_INGREDIENT: 12,
    BDISEASE_GROUP: 13,
    IDISEASE_GROUP: 14,
    BFOOD_GROUP: 15,
    IFOOD_GROUP: 16,
    BPERSON_GROUP: 17,
    IPERSON_GROUP: 18,
    BDRUG_GROUP: 19,
    IDRUG_GROUP: 20,
    BDRUG_DOSAGE: 21,
    IDRUG_DOSAGE: 22,
    BDRUG_TASTE: 23,
    IDRUG_TASTE: 24,
    BDRUG_EFFICACY: 25,
    IDRUG_EFFICACY: 26,
}
index2tag = {v: k for k, v in tag2indx.items()}
